version: '3.7'

networks:
  n1:
    external: true

services:

  dogsnet:
    image: amanohikaru/dogsnet
    # ports:
    #   - 3080:80
    #   - target: 80
    #     published: 80
    #     protocol: tcp
    #     mode: host
    networks:
      - n1
    deploy:
      placement:
        constraints:
          - node.labels.k1 == v1
      labels:
        - "traefik.port=80"
        - "traefik.enable=true"
        - "traefik.docker.network=n1"
        - "traefik.frontend.rule=PathPrefixStrip:/dogs/"     
        - traefik.frontend.entryPoints=http,https