version: '3.5'


networks:
  swarm_overlay:
    name: n1
    driver: overlay
    attachable: true
    
services:

  mysql:
    image: mysql:5.7
 #   restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /root/mysqlvolume:/var/lib/mysql
    networks:
      - swarm_overlay
    deploy:
      placement:
        constraints:
          - node.labels.k1 == v1
