version: '3.1'

services:

  mysql:
    image: mysql:5.7
 #   restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/mysqlvolume:/var/lib/mysql
