version: '3.7'


networks:
  n1:
    external: true

services:
  swTest:
    image: amanohikaru/swtest
    # ports:
    #   - target: 80
    #     published: 80
    #     protocol: tcp
    #     mode: host
    # volumes:
    #   - /etc/timezone:/etc/timezone:ro
    #   - /etc/localtime:/etc/localtime:ro

    deploy:

    networks:
      - n1
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.port=80"
        - "traefik.enable=true"
        - "traefik.docker.network=n1"
        - "traefik.frontend.rule=PathPrefixStrip:/test/"     
        - traefik.default.protocol=http