version: '3.1'



networks:
  n1:
    external: true


services:

  wordpress:
    image: wordpress
#    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: 39.104.226.149:3307
    networks:
      - n1
    deploy:
      placement:
        constraints: [node.role == manager]