
version: "3.2"

networks:
  n1:
    external: true

services:

  yellow_page:
    image: "amanohikaru/yellow_page"

    environment:
      TZ: Asia/Shanghai
    ports:
      - 10180:10180
    volumes:
      - /home/yellow_page:/home/yellow_page
    networks:
      - n1
    deploy:
      placement:
        constraints:
          - node.labels.k2 == v2
