
version: "3.5"

networks:
  n1:
    external: true

services:
  hexo-blog:
    image: "amanohikaru/hexo-blog"

    networks:
      - n1
    deploy:
      # placement:
      #   constraints:
      #     - node.labels.k2 == v2
      labels:
        - "traefik.port=80"
        - "traefik.enable=true"
        - "traefik.docker.network=n1"
        - "traefik.frontend.rule=PathPrefixStrip:/"     
        - traefik.frontend.entryPoints=http,https