version: "3.7"

networks:
  n1:
    external: true

services:
  traefik:
    image: traefik
    networks:
      - n1
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 9443
        protocol: tcp
        mode: host
      - 8001:8080
    configs:
      - source: my_config
        target: /etc/traefik/traefik.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

configs:
  my_config:
    file: ./traefik.toml

  # my_other_config:
  #   external: true